### ISSUE TITLE
Minimalny problem z rejestracją repo

### ISSUE THREAD

**Issue by Raytreq** [marcin-filipiak/cpp_studentmachine#4]
Podczas potwierdzania rejestracji repozytorium(punkt 10 w 3.2 w instrukcji) jeśli jest się planktonem i kliknie się enter zamiast y(myślałem, że y jest domyślne) skrypt się wywala. Nie jest to wielki problem, bo skrypt można odpalić jeszcze raz, ale wciąż

**Comment by marcin-filipiak** [comment]
dodana funkcja getch()
